### ISSUE TITLE
hash failing with json body

### ISSUE THREAD

**Issue by johndoe46** [tgs/requests-jwt#3]
``
import requests
import requests_jwt

jwt_auth = requests_jwt.JWTAuth("secret")
jwt_auth.add_field("body", requests_jwt.payload_body)

s = requests.Session()

resp = s.post("http://endpoint/", json={"some": "data"}, auth=jwt_auth)

File "/home/john/.local/lib/python3.6/site-packages/requests_jwt/__init__.py", line 48, in payload_body    'hash': hashlib.sha256(req.body.encode('utf-8')).hexdigest(),
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by tgs** [comment]
@johndoe46 - could you give it a try using 'master'?  If that works for you, I'll roll another release.

**Comment by tgs** [comment]
I released 0.5 (and 0.5.1 fixing a doc issue)
