### ISSUE TITLE
Unable to import version 0.5.1 after installation

### ISSUE THREAD

**Issue by verkaufer** [tgs/requests-jwt#4]
Version 0.5.1 introduced a breaking change that prevents users from successfully importing the package. 

After installing the package in a virtualenv I opened a python shell and ran:
```
>>> import requests_jwt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests_jwt'
```

Downgrading to `0.4` and pinning to 0.4 fixed the issue. 

There is another package that depends on `requests-jwt` that encountered this problem and also encountered this problem:
https://www.bountysource.com/issues/65317442-modulenotfounderror-no-module-named-requests_jwt

**Comment by tgs** [comment]
@verkaufer  -  sorry about that.  Fixed in 0.5.3, just uploaded to PyPI.
