### ISSUE TITLE
Compatibility with Python 3.7?

### ISSUE THREAD

**Issue by judyyang40** [tgs/requests-jwt#6]
Hi, 
I'm using requests_jwt as the Usage section in the readme. It's been working fine with Python 2.7, and once I moved to Python3, I started getting this error:

  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default                                                                                                              
    raise TypeError(f'Object of type {o.__class__.__name__} '                                                                                                                        
TypeError: Object of type bytes is not JSON serializable 

Is this a compatibility issue with Python3? 

Thanks!

**Comment by tgs** [comment]
Hello @judyyang40,
I know that some people have used it successfully with Python 3.  Could you give the complete backtrace? Are you able to make a short example that triggers the error?
Thanks!

**Comment by judyyang40** [comment]
Hi!
So it ended up being code on my side causing the issue... I was reading a file in 'rb' mode, which was ok in Python2, but not treated the same as Python3, and giving me the unserializable error.

**Comment by tgs** [comment]
Okay, glad you were able to resolve the issue! :+1:
